name: CI Pipeline

on: [push, pull_request]

jobs:
  build:

    # run build on latest ubuntu
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.6
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: mysecretpassword
          POSTGRES_DATABASE: my_database
        ports:
          - 5432:5432

    steps:
      # this will check out the current branch (https://github.com/actions/checkout#Push-a-commit-using-the-built-in-token)
      - uses: actions/checkout@v3
      # installing Node
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          # this will use the latest Node 12 version
          node-version: 16.x
      # install dependencies using clean install to avoid package lock updates
      - run: npm install
      # finally run the tests
      - run: npm run test:cov
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: mysecretpassword
          POSTGRES_DATABASE: my_database
      - name: Report test coverage to Coveralls
        run: npx coveralls < coverage/lcov.info
        env:
          COVERALLS_REPO_TOKEN: ${{ env.COVERALLS_REPO_TOKEN }}
